spring:
  datasource:
    url: jdbc:postgresql://postgres_server:5432/postgres    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:       ddl-auto: update
    generate-ddl: true
    show-sql: true